### ISSUE TITLE
Issue with direct links

### ISSUE THREAD

**Issue by mingan666** [bwdutton/gallery3-docker#9]
I've just succeeded to move and upgrade my old gallery and am currently running on docker.
I've also moved and upgraded my wordpress blog.

It all seems to be working fine except for direct links to the pictures that can be found in my blog.

For example (changed a bit for privacy)
```
http://gallery.example.com/index.php/album1/DSC07570-2
```
Such a link results in the following error message:
```
Dang... Something went wrong!
We tried really hard, but it's broken.
Talk to your Gallery administrator for help fixing this!
```
It can however be fixed with a workaround by first going to the main site (http://gallery.example.com) and then reload the direkt link it loads without issues.

The strange thing is that the blog post itself looks good.
The image tag in the post looks as follows:

```
<p style="text-align: center;"><a href="http://gallery.example.com/index.php/album1/DSC07570-2"><img class="g2image_normal" title="" src="http://gallery.example.com/var/resizes/album1/DSC07570-2.jpg?m=1394825421" alt="" /></a></p>
```

**Comment by bwdutton** [comment]
Are there any logs in the var/logs directory within the gallery directory? If so what are the errors?

**Comment by mingan666** [comment]
```
2022-01-02 19:00:37 +00:00 --- error: ErrorException [ 0 ]: Trying to access array offset on value of type null
/var/www/html/modules/gallery/helpers/item.php [ 459 ]
#0 /var/www/html/modules/gallery/helpers/item.php(459): gallery_error_Core::error_handler(2, 'Trying to acces...', '/var/www/html/m...', 459)
#1 /var/www/html/modules/gallery/controllers/photos.php(34): item_Core::get_display_context(Object(Item_Model))
#2 [internal function]: Photos_Controller->show(Object(Item_Model))
#3 /var/www/html/system/core/Kohana.php(302): ReflectionMethod->invokeArgs(Object(Photos_Controller), Array)
#4 /var/www/html/system/core/Event.php(208): Kohana_Core::instance(NULL)
#5 /var/www/html/application/Bootstrap.php(67): Event_Core::run('system.execute')
#6 /var/www/html/index.php(124): require('/var/www/html/a...')
```

**Comment by mingan666** [comment]
But that seems to be an error that keeps coming.
Sorry, didn't even know the log directory was there...

Seems something is strange with my installation?

**Comment by bwdutton** [comment]
How does your docker usage vary from the example config?
https://github.com/bwdutton/gallery3-docker/blob/master/docker-compose.yml
I tried to replicate what you are seeing on my gallery/container but couldn't replicate. I thought maybe if the URLs had permissions assigned it would cause the error but that worked as expected too.
The error/code in question does seem session related but I'm not yet sure how/why to reproduce the issue.

**Comment by mingan666** [comment]
It a bit different since I run on a docker swarm and use traefik proxy:

```
  gallery:
    image: bwdutton/gallery3:3.1.5
    volumes:
      - gallery:/var/www/html/var
    networks:
      - traefik_proxy
      - net
    environment:
      - DEVELOPMENT=1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gallery.rule=Host(`gallery.example.com`)
        - traefik.http.routers.gallery-secure.entrypoints=web
        - "traefik.http.routers.gallery.middlewares=https-redirect@file"
        - traefik.http.routers.gallery-secure.rule=Host(`gallery.example.com`)
        - traefik.http.routers.gallery-secure.entrypoints=websecure
        - traefik.http.routers.gallery-secure.tls.certresolver=letsencryptresolver
        - traefik.http.services.gallery.loadbalancer.server.port=80
```

I had som other issues with gallery behind traefik... It worked most of the time, but for example login/logout could give me http links back instead of https. I added the redirect as a workaround. Now any http requests to this host are redirected to https.

If you want I could do some additional testing during the weekend. Trying the same compose file with a clean installation? As I said I tried to move my old  3.0.9 gallery from my nas to a docker stack.

**Comment by bwdutton** [comment]
Use the SITE_PROTOCOL environment setting as directed on here:
https://hub.docker.com/r/bwdutton/gallery3
That will fix the http/https issues with Traefik (I run that as well).

**Comment by mingan666** [comment]
I've tried that as well, but it didn't seem to work. I think it has to do with the fact that the gallery service does not have a proper certificate of itself. So traefik refuses to proxy to its https port.

The following config gives bad gateway in the browser:
```
  gallery:
    image: bwdutton/gallery3:3.1.5
    volumes:
      - gallery:/var/www/html/var
    networks:
      - traefik_proxy
      - net
    environment:
      - DEVELOPMENT=1
      - SITE_PROTOCOL="https"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gallery.rule=Host(`gallery.example.com`)
        - traefik.http.routers.gallery-secure.entrypoints=web
        - "traefik.http.routers.gallery.middlewares=https-redirect@file"
        - traefik.http.routers.gallery-secure.rule=Host(`gallery.example.com`)
        - traefik.http.routers.gallery-secure.entrypoints=websecure
        - traefik.http.routers.gallery-secure.tls.certresolver=letsencryptresolver
        - traefik.http.services.gallery.loadbalancer.server.port=443
```
